#!/bin/sh

TARGETS=`ls *.c`
SRC="`echo \"${TARGETS}\" | fmt -60 | sed -e 's/^/	/' -e '$!s/$/ \\\/'`"
BIN=`echo "$SRC" | sed 's/\.c//g'`

cat <<EOF
# XXX Autogenerated - do not edit
# Makefile for cs201 C examples

CC = gcc
CFLAGS = -Wall -g

SRC = $SRC

BIN = $BIN

all: \$(BIN)

EOF

for S in $TARGETS
do
    B=`echo $S | sed 's/\.c//'`
    echo "$B: $S"
    M="\$(CC) \$(CFLAGS) -o $B $S"
    if [ -f $B.mk ]
    then
        M="`cat $B.mk`"
    fi
    echo "	$M"
    echo ""
done

cat <<EOF
clean:
	-rm -f \$(BIN)
EOF
